// https://leetcode.com/problems/find-the-difference/

// You are given two strings s and t.
// String t is generated by random shuffling string s and then add one more letter at a random position.
// Return the letter that was added to t. 

// Example 1:
// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.

// Example 2:
// Input: s = "", t = "y"
// Output: "y"

// Constraints:
//     0 <= s.length <= 1000
//     t.length == s.length + 1
//     s and t consist of lowercase English letters.

const findTheDifference = (s, t) => {
    const letterFinder = {}
    const answer = []
    for (let i = 0; i < t.length; i++) {
        let key = t[i]
        if (!letterFinder[key]) letterFinder[key] = 1
        else letterFinder[key]++
    }
    console.log(letterFinder)
    for (let i = 0; i < s.length; i++) {
        key = s[i]
        letterFinder[key]--
    }
    for (let i = 0; i < t.length; i++) {
        key = t[i]
        if (letterFinder[key] >= 1) {
            answer.push(t[i])
            console.log("answer:", answer.join(""))
            return answer.join("")
            }
        }
    }

findTheDifference("a", "aa")